name: Windows-RDP-2025
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setting Up RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Install Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip
    - name: Connect to Ngrok
      run: |
        .\ngrok.exe authtoken "31bRwOPoJXHLXBD8L4lMqW7QHVN_4MArhYTk13MZP9TSiksh8"
        Start-Process .\ngrok.exe -ArgumentList "tcp 3389"
    - name: Keep Alive
      run: |
        $script = { while($true){ sleep 60 } }
        Invoke-Command -ScriptBlock $script
